# Generated by Django 3.0.5 on 2020-04-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='checking_now',
            field=models.BooleanField(default=False),
        ),
    ]
